# gradle/libs.versions.toml

[versions]
# AndroidX
core-ktx = "1.15.0"
appcompat = "1.7.0"
recyclerview = "1.3.2"
lifecycle-extensions = "2.2.0"
lifecycle-viewmodel-ktx = "2.8.7"
navigation-fragment-ktx = "2.8.4"
navigation-ui-ktx = "2.8.4"
constraintlayout = "2.2.0"
constraintlayout-compose = "1.1.0"
work-runtime-ktx = "2.10.0"
biometric-ktx = "1.4.0-alpha02"
activity-compose = "1.9.3"

# Compose Material
compose-material = "1.7.5"
compose-animation = "1.7.5"
compose-ui = "1.7.5"
compose-foundation = "1.7.5"
compose-ui-tooling = "1.7.5"

# Libraries
commons-text = "1.12.0"
gson = "2.11.0"
color-chooser = "0.7.3"
compose-colorful-sliders = "1.2.0"

# ACRA
acra = "5.11.3"

# Android Test
espresso = "3.6.1"
test-runner = "1.6.2"
test-rules = "1.6.1"
test-core-ktx = "1.6.1"

# Debug/Test
fragment-testing = "1.8.5"
ui-test-junit4 = "1.7.5"
ui-test-manifest = "1.7.5"
navigation-testing = "2.8.4"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }
biometric-ktx = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometric-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-material" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose-animation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui-tooling" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
color-chooser = { group = "net.mm2d.color-chooser", name = "color-chooser", version.ref = "color-chooser" }
compose-colorful-sliders = { group = "com.github.SmartToolFactory", name = "Compose-Colorful-Sliders", version.ref = "compose-colorful-sliders" }
acra-core = { group = "ch.acra", name = "acra-core", version.ref = "acra" }
acra-dialog = { group = "ch.acra", name = "acra-dialog", version.ref = "acra" }
acra-mail = { group = "ch.acra", name = "acra-mail", version.ref = "acra" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core-ktx" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment-testing" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "ui-test-manifest" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation-testing" }
