name: Question
description: Ask about anything related
labels: ['Type: Question']
title: '[Question] add text here'
assignees: ['CreativeCodeCat']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! :hugs:

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I will make sure to have the issue written in English with an English title."
          required: true
        - label: "I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to."
          required: true
        - label: "I have already checked the [WIKI](https://github.com/DroidWorksStudio/mLauncher/wiki) pages."
          required: true
        - label: "I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md)."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise."
          required: true
        - label: "I optionally [donated](https://www.buymeacoffee.com/CreativeCodeCat) to support the mLauncher mission."
          required: false

  - type: textarea
    id: what-is-the-question
    attributes:
      label: What is/are your question(s)?
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include.

  - type: checkboxes
    id: checklist-accept
    attributes:
      label: "Terms and Conditions"
      options:
        - label: "I have read all the rules above and filled in the requiered fields to the best of my ability."
          required: true
        - label: "I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project."
          required: true
