name: Build Android Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Copy debug apk for the artifacts
      run:  cp ./app/build/outputs/apk/release/app-release-unsigned.apk app-release-${{ steps.date.outputs.date }}.apk
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: app-release-${{ steps.date.outputs.date }}.apk
        path: app-release-${{ steps.date.outputs.date }}.apk
