name: Update CHANGELOG.md

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          token: ${{ github.actor == 'dependabot[bot]' && secrets.GITHUB_TOKEN || secrets.GIT_BOT_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'  # or whatever version you need

      - name: Run changelog script
        run: |
          node generate-changelog.js --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(changelog): Update CHANGELOG.md"
            git push
          fi
