name: Update CHANGELOG.md

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          token: ${{ github.actor == 'dependabot[bot]' && secrets.GITHUB_TOKEN || secrets.GIT_BOT_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Install Rust (required for git-cliff)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Generate changelog for last 5 tags
        run: |
          LAST_TAG=$(git tag --sort=-creatordate | head -n 10 | tail -n 1)
          git-cliff "$LAST_TAG..HEAD" -o CHANGELOG.md --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(changelog): Update CHANGELOG.md"
            git push
          fi
