name: Validate Gradle Wrapper

on:
  push:
    branches:
      - '*'
      - '!translate_main'
  pull_request:
    branches:
      - 'main'

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/wrapper-validation-action@v3.5.0
